%PDF-1.4
%‚„œ”
3 0 obj <</Length 139/Filter/FlateDecode>>stream
xúUé±
¬@D˚˘ä-µY˜rõ‹•,b5ÑDåçøÔùêÄl3ofXf¬÷ ’qåd-vÜÑ≈áí>(ËòÚNËÑÀU®ÖF
µœ˝•.f÷»¢	ıO.≠g<”€|ÔGû∞Ÿ;r5ódw∏üÔH3≠∏Úd#Vá€Z[?Ol≤&ä
endstream
endobj
1 0 obj<</Parent 4 0 R/Contents 3 0 R/Type/Page/Resources<</ProcSet [/PDF /Text /ImageB /ImageC /ImageI]/Font<</F1 2 0 R>>>>/MediaBox[0 0 595.28 841.88]>>
endobj
2 0 obj<</BaseFont/Helvetica-Bold/Type/Font/Encoding/WinAnsiEncoding/Subtype/Type1>>
endobj
4 0 obj<</Type/Pages/Count 1/Kids[1 0 R]>>
endobj
5 0 obj<</Type/Catalog/Pages 4 0 R>>
endobj
6 0 obj<</Producer(iText 2.0.8 \(by lowagie.com\))/ModDate(D:20130127172401Z)/CreationDate(D:20130127172401Z)>>
endobj
xref
0 7
0000000000 65535 f 
0000000221 00000 n 
0000000383 00000 n 
0000000015 00000 n 
0000000475 00000 n 
0000000525 00000 n 
0000000569 00000 n 
trailer
<</Root 5 0 R/ID [<de278cf5a3fd5d274a7cc956cb6caa8f><83fc08e4ecd5a96522b68c72778992a4>]/Info 6 0 R/Size 7>>
startxref
688
%%EOF
